apiVersion: v1
kind: Service
metadata:
  name: {{ include "voter.fullname" . }}
  labels:
{{ include "voter.labels" . | indent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.vote.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "voter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}